# Generated by Django 4.2.2 on 2024-02-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='inventory',
            field=models.IntegerField(default=0, help_text='inventory', verbose_name='库存'),
        ),
    ]
