version: "3"

services:
  blog_nginx:
    build:
      context: blog_nginx
    image: blog_nginx
    container_name: blog_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - blog_ssr
      - blog_server
    ulimits:
      nproc: 65535
      nofile:
        soft: 100000
        hard: 200000
    networks:
      - blogs



networks:
  blogs:
    driver: bridge
