version: "3"


services:
  blog_server:
    build:
      context: ./blog_server
    volumes:
      - ./blog_server/static/:/blog_server/static/
    ports:
      - "8000:8000"
    image: blog_server
    container_name: blog_server
    networks:
      - blogs

  blog_site:
    build:
      context: ./blog_site
    image: blog_site
    container_name: blog_site

  blog_ssr:
    build:
      context: ./blog_ssr
    depends_on:
      - blog_site
    ports:
      - "8001:8001"
    image: blog_ssr
    container_name: blog_ssr
    networks:
      - blogs


networks:
  blogs:
    driver: bridge
