version: "3"

services:
  blog_server:
    build:
      context: ./blog_server
    volumes:
      - ./blog_server/static/:/blog_server/static/
    ports:
      - "8000:8000"
    image: blog_server
    container_name: blog_server

