# Generated by Django 3.2.9 on 2022-01-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.CharField(blank=True, help_text='description', max_length=255, null=True),
        ),
    ]
