# Generated by Django 3.2.9 on 2022-01-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_picture_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.CharField(blank=True, help_text='description', max_length=255),
        ),
    ]
