# Generated by Django 3.2.9 on 2022-01-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_alter_picture_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(default='test.jprg', help_text='name', max_length=255),
            preserve_default=False,
        ),
    ]
