# Generated by Django 3.2.9 on 2022-04-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0005_picture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='height',
            field=models.IntegerField(default=100, help_text='height'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='width',
            field=models.IntegerField(default=100, help_text='width'),
            preserve_default=False,
        ),
    ]
