# Generated by Django 3.2.9 on 2022-04-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0006_auto_20220413_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='unique_name',
            field=models.CharField(default='ssssss', help_text='unique name', max_length=255),
            preserve_default=False,
        ),
    ]
