# Generated by Django 3.2.9 on 2022-08-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0007_picture_unique_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-update_time'], 'verbose_name': 'picture', 'verbose_name_plural': 'picture'},
        ),
        migrations.AddField(
            model_name='picture',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='update at'),
        ),
    ]
