# Generated by Django 3.2.9 on 2022-08-28 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0008_auto_20220828_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-create_time'], 'verbose_name': 'picture', 'verbose_name_plural': 'picture'},
        ),
    ]
