# Generated by Django 4.2.2 on 2024-03-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='title', max_length=255, null=True, verbose_name='标题'),
        ),
    ]
