# Generated by Django 3.2.9 on 2022-01-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='description',
            field=models.CharField(blank=True, help_text='description', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='author',
            field=models.CharField(blank=True, help_text='author', max_length=255, null=True),
        ),
    ]
