# Generated by Django 3.2.9 on 2022-01-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20220102_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['title'], 'verbose_name': 'text', 'verbose_name_plural': 'text'},
        ),
    ]
