# Generated by Django 3.2.9 on 2022-08-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_alter_text_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['-update_time'], 'verbose_name': 'text', 'verbose_name_plural': 'text'},
        ),
    ]
