# Generated by Django 3.2.9 on 2021-12-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title', max_length=255, unique=True)),
                ('content', models.TextField(help_text='content')),
                ('author', models.CharField(help_text='author', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update at')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blog',
                'ordering': ['title'],
            },
        ),
    ]
