# Generated by Django 3.2.9 on 2021-12-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={'ordering': ['title'], 'verbose_name': 'draft', 'verbose_name_plural': 'draft'},
        ),
    ]
