# Generated by Django 3.2.9 on 2022-08-28 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0006_alter_draft_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={'ordering': ['-create_time'], 'verbose_name': 'draft', 'verbose_name_plural': 'draft'},
        ),
    ]
