# Generated by Django 4.2.2 on 2024-03-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='name', max_length=255, null=True, verbose_name='标题')),
                ('content', models.TextField(help_text='content', max_length=255, verbose_name='内容')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True)),
                ('view', models.IntegerField(default=0, help_text='view', verbose_name='浏览量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'ordering': ['-create_time'],
            },
        ),
    ]
